"""
Omni-Connect Retail Copilot Portal - Streamlit UI.

Empty application scaffold. Wire the business-data services (src/services/),
the knowledge base (data/knowledge_base/), and the recommendation pipeline
into this portal as the starter app matures. Mirrors the bootcamp
streamlit_app.py conventions (system path wiring + page config).

Run:  streamlit run app/portal.py
"""
import sys
from pathlib import Path

import streamlit as st

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

st.set_page_config(
    page_title="Omni-Connect Retail Copilot Portal",
    page_icon="📡",
    layout="wide",
    initial_sidebar_state="expanded",
)

st.markdown(
    """
<style>
    .main-header {font-size: 2.4rem; color: #1f4788; font-weight: bold;}
    .sub-header {font-size: 1.1rem; color: #555; margin-bottom: 1.5rem;}
    .footer {position: fixed; left: 0; bottom: 0; width: 100%; background-color: #f5f5f5;
             text-align: center; padding: 0.5rem 1rem; font-size: 0.85rem; color: #777;
             border-top: 1px solid #ddd; z-index: 100;}
</style>
""",
    unsafe_allow_html=True,
)

st.markdown('<div class="main-header">📡 Omni-Connect Retail Copilot Portal</div>', unsafe_allow_html=True)
st.markdown(
    '<div class="sub-header">Retail copilot for plan, device, billing, and promotion recommendations</div>',
    unsafe_allow_html=True,
)

with st.sidebar:
    st.header("Platform Status")
    st.info("Empty scaffold - platform components not wired yet.")
    st.divider()
    st.caption("Omni-Connect Retail Copilot · Starter App")

st.markdown('<div class="sub-header">Workspace</div>', unsafe_allow_html=True)

catalog_col, promotion_col, billing_col = st.columns(3)

with catalog_col:
    with st.container(border=True):
        st.subheader("Customer")
        st.caption("crm_records.json + billing_records.json")
        st.info("Customer data coming soon.")

with promotion_col:
    with st.container(border=True):
        st.subheader("Agent")
        st.caption("recommendation pipeline")
        st.info("Agent outputs coming soon.")

with billing_col:
    with st.container(border=True):
        st.subheader("Decision")
        st.caption("workflow output")
        st.info("Decisions coming soon.")

st.markdown(
    '<div class="footer">© 2026 Omni-Connect Retail Copilot · Demo data is synthetic and generated by scripts/</div>',
    unsafe_allow_html=True,
)